### ISSUE TITLE
[Bug] Max webhooks. Unable to clear without restarting.

### ISSUE THREAD

**Issue by alicat22** [WaywardWyvernsSoftworks/TalOS#38]
**Describe the bug**
Doesn't allow you to clear webhooks when max limit is reached. You have to restart the server first.

**To Reproduce**
1. Add 15 webooks
2. Generate a message using another webhook
3. See error.

**Expected behavior**
Error message. Then /clearwebhooks without restarting server.

**Desktop (please complete the following information):**
 - Device: desktop
 - OS: windows
 - Browser chrome

**Additional context**
Error message:
```
}
DiscordAPIError[30007]: Maximum number of webhooks reached (15)
    at handleErrors (H:\AI\ConstructOS\node_modules\@discordjs\rest\dist\index.js:687:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (H:\AI\ConstructOS\node_modules\@discordjs\rest\dist\index.js:1072:23)
    at async SequentialHandler.queueRequest (H:\AI\ConstructOS\node_modules\@discordjs\rest\dist\index.js:913:14)
    at async _REST.request (H:\AI\ConstructOS\node_modules\@discordjs\rest\dist\index.js:1218:22)
    at async GuildChannelManager.createWebhook (H:\AI\ConstructOS\node_modules\discord.js\src\managers\GuildChannelManager.js:222:18)
    at async createWebhookForChannel (H:\AI\ConstructOS\dist-electron\main\index.js:5283:15)
    at async sendMessageAsCharacter (H:\AI\ConstructOS\dist-electron\main\index.js:5245:15)
    at async doRoundRobin (H:\AI\ConstructOS\dist-electron\main\index.js:3470:7)
    at async continueChatLog (H:\AI\ConstructOS\dist-electron\main\index.js:3524:17) {
  requestBody: {
    files: undefined,
    json: {
      name: 'Empyrea',
      avatar: 'data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAZAAAAJYCAY...
    }
  },
  rawError: { message: 'Maximum number of webhooks reached (15)', code: 30007 },
  code: 30007,
  status: 400,
  method: 'POST',
  url: 'https://discord.com/api/v10/channels/1123811228876275753/webhooks'
}
```

**Comment by thesentinel2615** [comment]
Fixed awhile ago :))
